# Visualization pipeline component 1 (Updated for high visibility)
## Structural rendering grid for distribution metric properties with enhanced contrast

import matplotlib.pyplot as plt

def plot_variance_vs_iqr_distribution(df_stats: pd.DataFrame) -> plt.Figure:
    """
    Render a composite matrix layout mapping Raw Variance and Rolling IQR dispersion metrics.
    Enhanced with high-contrast line weights, distinct alpha levels, and scannable colors.

    :param df_stats: Aggregated metrics generated by compute_stability_indices.
    :type df_stats: pd.DataFrame
    :return: Matplotlib figure instance.
    :rtype: plt.Figure
    """
    interpreters = sorted(df_stats['interpreter'].unique())
    optimizers = sorted(df_stats['optimizer'].unique())
    metrics = ['score_deepstarr', 'score_deepstarr_second', 'score_original_modified']
    
    # High-contrast professional palette selection
    color_map = {
        'score_deepstarr': '#1a73e8',          # Vibrant Cobalt Blue
        'score_deepstarr_second': '#e67e22',   # Deep Amber Orange
        'score_original_modified': '#2ea44f'   # Emerald Green
    }
    lbl_map = {
        'score_deepstarr': 'deepstarr', 
        'score_deepstarr_second': 'deepstarr_second', 
        'score_original_modified': 'original_modified'
    }
    
    fig, axes = plt.subplots(len(optimizers), len(interpreters), figsize=(16, 11), sharex=True, sharey=True, squeeze=False)
    legend_handles = {}

    # Layout generation loop
    for r_idx, opt in enumerate(optimizers):
        for c_idx, interp in enumerate(interpreters):
            ax = axes[r_idx, c_idx]
            sub_df = df_stats[(df_stats['interpreter'] == interp) & (df_stats['optimizer'] == opt)].sort_values('iteration')
            
            for m in metrics:
                if sub_df.empty:
                    continue
                color = color_map[m]
                
                ### Case 1: Raw Variance (Dashed style for visibility, increased width)
                h_var, = ax.plot(
                    sub_df['iteration'], sub_df[f'{m}_var_mean'], 
                    color=color, linestyle='--', alpha=0.65, linewidth=1.8
                )
                ax.fill_between(
                    sub_df['iteration'], 
                    np.maximum(0, sub_df[f'{m}_var_mean'] - sub_df[f'{m}_var_std']), 
                    sub_df[f'{m}_var_mean'] + sub_df[f'{m}_var_std'], 
                    color=color, alpha=0.05
                )
                
                ### Case 2: Rolling IQR (Bold solid line style, high saturation)
                h_iqr, = ax.plot(
                    sub_df['iteration'], sub_df[f'{m}_iqr_mean'], 
                    color=color, linestyle='-', alpha=0.95, linewidth=3.0
                )
                ax.fill_between(
                    sub_df['iteration'], 
                    np.maximum(0, sub_df[f'{m}_iqr_mean'] - sub_df[f'{m}_iqr_std']), 
                    sub_df[f'{m}_iqr_mean'] + sub_df[f'{m}_iqr_std'], 
                    color=color, alpha=0.22
                )
                
                if lbl_map[m] not in legend_handles:
                    legend_handles[lbl_map[m]] = (h_var, h_iqr)
            
            # Subplot grid tuning
            ax.grid(True, linestyle='--', alpha=0.45, linewidth=0.7)
            ax.tick_params(labelsize=9)

    # Outer decoration boundaries configuration
    for col_idx, interp in enumerate(interpreters):
        axes[0, col_idx].set_title(f"Interpreter: {interp}", fontsize=12, fontweight='bold', pad=12)
    for r_idx, opt in enumerate(optimizers):
        axes[r_idx, 0].set_ylabel(f"Optimizer: {opt}\n\nMetric Spread", fontsize=10, fontweight='bold', labelpad=15)
    for col_idx in range(len(interpreters)):
        axes[-1, col_idx].set_xlabel("Optimization Iterations", fontsize=11, fontweight='bold', labelpad=10)

    ## Flattened clear legend definition outside plotting space
    handles, labels = [], []
    for k, (h_v, h_i) in legend_handles.items():
        handles.extend([h_v, h_i])
        labels.extend([f"{k} ($\\sigma^2$)", f"{k} (IQR)"])
        
    fig.legend(handles=handles, labels=labels, loc='center right', bbox_to_anchor=(0.99, 0.5), fontsize=10, frameon=True, facecolor='white', framealpha=0.95)
    plt.subplots_adjust(left=0.09, right=0.83, top=0.93, bottom=0.07, hspace=0.15, wspace=0.15)
    return fig


# Visualization pipeline component 2 (Updated for high visibility)
## Structural rendering grid for unified mathematical stability index metrics

def plot_stability_index_comparison(df_stats: pd.DataFrame) -> plt.Figure:
    """
    Render a composite matrix layout grid comparing scaled stability index responses.
    Optimized line structures and robust alpha properties eliminate visibility degradation.

    :param df_stats: Aggregated metrics generated by compute_stability_indices.
    :type df_stats: pd.DataFrame
    :return: Matplotlib figure instance.
    :rtype: plt.Figure
    """
    interpreters = sorted(df_stats['interpreter'].unique())
    optimizers = sorted(df_stats['optimizer'].unique())
    metrics = ['score_deepstarr', 'score_deepstarr_second', 'score_original_modified']
    
    # High-contrast professional palette selection
    color_map = {
        'score_deepstarr': '#1a73e8',          # Vibrant Cobalt Blue
        'score_deepstarr_second': '#e67e22',   # Deep Amber Orange
        'score_original_modified': '#2ea44f'   # Emerald Green
    }
    lbl_map = {
        'score_deepstarr': 'deepstarr', 
        'score_deepstarr_second': 'deepstarr_second', 
        'score_original_modified': 'original_modified'
    }
    
    fig, axes = plt.subplots(len(optimizers), len(interpreters), figsize=(16, 11), sharex=True, sharey=True, squeeze=False)
    legend_handles = {}

    # Layout generation loop
    for r_idx, opt in enumerate(optimizers):
        for c_idx, interp in enumerate(interpreters):
            ax = axes[r_idx, c_idx]
            sub_df = df_stats[(df_stats['interpreter'] == interp) & (df_stats['optimizer'] == opt)].sort_values('iteration')
            
            for m in metrics:
                if sub_df.empty:
                    continue
                color = color_map[m]
                
                ### Plot variance stability metric transformation (Thicker dashed line for clear indexing tracks)
                h_v_idx, = ax.plot(
                    sub_df['iteration'], sub_df[f'{m}_stab_v_mean'], 
                    color=color, linestyle='--', alpha=0.65, linewidth=1.8
                )
                ax.fill_between(
                    sub_df['iteration'], 
                    np.clip(sub_df[f'{m}_stab_v_mean'] - sub_df[f'{m}_stab_v_std'], 0, 1), 
                    np.clip(sub_df[f'{m}_stab_v_mean'] + sub_df[f'{m}_stab_v_std'], 0, 1), 
                    color=color, alpha=0.05
                )
                
                ### Plot rolling IQR stability index response (Heavyweight solid line)
                h_i_idx, = ax.plot(
                    sub_df['iteration'], sub_df[f'{m}_stab_i_mean'], 
                    color=color, linestyle='-', alpha=0.95, linewidth=3.0
                )
                ax.fill_between(
                    sub_df['iteration'], 
                    np.clip(sub_df[f'{m}_stab_i_mean'] - sub_df[f'{m}_stab_i_std'], 0, 1), 
                    np.clip(sub_df[f'{m}_stab_i_mean'] + sub_df[f'{m}_stab_i_std'], 0, 1), 
                    color=color, alpha=0.20
                )
                
                if lbl_map[m] not in legend_handles:
                    legend_handles[lbl_map[m]] = (h_v_idx, h_i_idx)
            
            ax.set_ylim(0, 1.05)
            ax.grid(True, linestyle='--', alpha=0.45, linewidth=0.7)
            ax.tick_params(labelsize=9)

    # Outer decoration boundaries configuration
    for col_idx, interp in enumerate(interpreters):
        axes[0, col_idx].set_title(f"Interpreter: {interp}", fontsize=12, fontweight='bold', pad=12)
    for r_idx, opt in enumerate(optimizers):
        axes[r_idx, 0].set_ylabel(f"Optimizer: {opt}\n\nStability Index", fontsize=10, fontweight='bold', labelpad=15)
    for col_idx in range(len(interpreters)):
        axes[-1, col_idx].set_xlabel("Optimization Iterations", fontsize=11, fontweight='bold', labelpad=10)

    ## Flattened clear legend definition outside plotting space
    handles, labels = [], []
    for k, (h_v, h_i) in legend_handles.items():
        handles.extend([h_v, h_i])
        labels.extend([f"{k} ($1/(1+\\sigma^2)$)", f"{k} ($w(t)$ IQR)"])
        
    fig.legend(handles=handles, labels=labels, loc='center right', bbox_to_anchor=(0.99, 0.5), fontsize=10, frameon=True, facecolor='white', framealpha=0.95)
    plt.subplots_adjust(left=0.09, right=0.83, top=0.93, bottom=0.07, hspace=0.15, wspace=0.15)
    return fig